version: '3.9'
services:
  pg-access-apply:
    build: .
    command:
      - npm
      - test
    environment:
      PG_HOST: pg
      PG_USERNAME: postgres
      PG_PASSWORD: pg
      PG_PORT: 5432
    depends_on:
      - pg

  pg:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: pg
