name: "Run linting and tests"

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:focal

    services:
      pg:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: pg
        options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-timeout 5s
            --health-retries 5

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run compile

    - run: npm run lint-check
    - run: npm run _generate-types
      env:
        ERROR_ON_CHANGES: 'yes'
    - run: npm run test
      env:
        PG_HOST: pg
        PG_USERNAME: postgres
        PG_PASSWORD: pg
        PG_PORT: 5432
